version: '3'

tasks:
  default:
    desc: list tasks
    cmds:
      - task --list-all

  stop:
    desc: terminate application
    cmds:
      - docker-compose down --volumes

  start:
    desc: run application
    deps:
      - stop
    cmds:
      - docker-compose up -d --build --force-recreate

  logs:
    desc: run logs
    cmds:
      - docker-compose logs -f